updated frontend precommit script. added restoring staged files on script fail

diff --git a/frontend/.husky/pre-commit b/frontend/.husky/pre-commit
--- a/frontend/.husky/pre-commit
+++ b/frontend/.husky/pre-commit
@@ -4,15 +4,24 @@ CURRENT_DIR=$(pwd)
 
 CHANGED_FILES=$(git diff --cached --name-only)
 
+handle_error() {
+  echo "$1 failed in $2. Restoring staged changes..."
+  git restore --staged "$REPO_ROOT/$2"
+  exit 1
+}
+
 run_lint() {
   echo "Testing $1 folder..."
   cd "$REPO_ROOT/$1" || exit 1
-  npm run lint
+
+  npm run lint || handle_error "Linting" "$1"
   npm run lint:auto-fix
   npm run lint:format
+
   git add .
   cd "$CURRENT_DIR" || exit 1
 }
+
 
 if echo "$CHANGED_FILES" | grep -qE '^frontend/' && echo "$CHANGED_FILES" | grep -qE '^web-frontend/'; then
   echo "BOTH FOLDERS: WEB-FRONTEND AND FRONTEND CHANGED -> running test for both of them..."
